/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClanRainbow.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                title: 'Calendario',
                iconCls: 'time',
                html: '<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTz=0&amp;height=200&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=ousovf39nb78d68aaammf5dnqk%40group.calendar.google.com&amp;color=%23A32929&amp;ctz=Europe%2FRome" style=" border-width:0 " frameborder="0" scrolling="no"></iframe>',
                id: 'calendarView'
            },
            {
                xtype: 'container',
                title: 'Il Clan',
                iconCls: 'team',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'carousel',
                        items: [
                            {
                                xtype: 'container',
                                html: 'IL CLAN PAGINA 1'
                            },
                            {
                                xtype: 'container',
                                html: 'IL CLAN PAGINA 2'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                iconCls: 'arrow_left',
                                iconMask: true
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'label',
                                html: 'IL CLAN'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                iconAlign: 'right',
                                iconCls: 'arrow_right',
                                iconMask: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Carta di Clan',
                iconCls: 'bookmarks',
                html: 'carta di clan',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'label',
                                html: 'CARTA DI CLAN'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Capitolo',
                iconCls: 'compose',
                items: [
                    {
                        xtype: 'container',
                        title: 'Lavoro e Futuro'
                    },
                    {
                        xtype: 'container',
                        title: 'Analisi'
                    },
                    {
                        xtype: 'container',
                        title: 'Problematiche'
                    },
                    {
                        xtype: 'container',
                        title: 'Aspettative'
                    },
                    {
                        xtype: 'container',
                        title: 'Opportunità'
                    }
                ],
                tabBar: {
                    docked: 'top'
                }
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});