/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({

});

Ext.application({

    requires: [
        'Ext.carousel.Carousel',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.Panel'
    ],
    models: [
        'Event'
    ],
    stores: [
        'EventStore'
    ],
    views: [
        'MyTabPanel'
    ],
    controllers: [
        'CalendarController'
    ],
    name: 'ClanRainbow',

    launch: function() {
        //this.getController('CalendarController').initCalendarView();

        Ext.create('ClanRainbow.view.MyTabPanel', {fullscreen: true});
    }

});
