/*
 * File: app/controller/CalendarController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClanRainbow.controller.CalendarController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            calendarView: '#calendarView'
        },

        control: {
            "#calendarView": {
                activate: 'onContainerActivate'
            }
        }
    },

    onContainerActivate: function(container, newActiveItem, oldActiveItem, options) {
        this.initCalendarView();
    },

    init: function(application) {
        this.calendarTpl = new Ext.XTemplate('<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTz=0&amp;height=200&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=ousovf39nb78d68aaammf5dnqk%40group.calendar.google.com&amp;color=%23A32929&amp;ctz=Europe%2FRome" style=" border-width:0 " width="{width}" height="{height}" frameborder="0" scrolling="no"></iframe>');

    },

    initCalendarView: function() {
        var docWidth = document.width;
        var docHeight = document.height; 
        var calendarHtml=this.calendarTpl.apply({width:docWidth -10, height:docHeight - 30});
        this.getCalendarView().setHtml(calendarHtml);
    }

});